
flowchart TB
    A["DropletCounter Init"] --> B["Connect to Fraction Collector"]
    B --> C["Set Remote Mode"]
    C --> D["Set Collect Mode"]
    D --> E["Initialize Experiment Settings"]
    E --> F["Start New Run"]
    F --> G["Set Flowrate"]
    G --> H{"First Run?"}
    H -- Yes --> I["Wait for Steady State"]
    H -- No --> J["Activate Measurement Timer"]
    I --> J
    J --> K["Start Timer - Poll Every 5s"]
    K --> L["Poll Droplet Count"]
    L --> M["Record Timestamp & Count"]
    M --> N{"Duration >= Max Duration?"}
    N -- No --> L
    N -- Yes --> O["Stop Timer"]
    O --> P["Calculate Run Average"]
    P --> Q["Append Records to Master list"]
    Q --> R{"More Runs for Flowrate?"}
    R -- Yes --> S["run index =+ 1"]
    S --> F
    R -- No --> T["Calculate Overall Average"]
    T --> U["Update Master Records"]
    U --> V{"More Flowrates? (0.1, 0.25, 0.5, etc)"}
    V -- Yes --> W["Flowrate Index =+ 1"]
    W --> F
    V -- No --> X["Calculate Calibration Gradient"]
    X --> Y["Save Master CSV"]
    Y --> Z["Calculate Calibration Factor (accurate gradient/ calibration gradient)"]
    Z --> AA["Update Widget"]
    AA --> AB["Disconnect Hardware"]
    AB --> AC["End"]
